--DROP TABLE IF EXISTS clientes;
--
--CREATE TABLE cliente (
--       id_cliente BIGINT AUTO_INCREMENT NOT NULL,
--       nome VARCHAR(255) NULL,
--       renda DOUBLE NULL,
--       Primary KEY (id_cliente));